### ISSUE TITLE
Exception being thrown from SqlTiming

### ISSUE THREAD

**Issue by kzhen** [MiniProfiler/dotnet#113]
Hi, 

I'm using Mini Profiler with Nancy (rather than ASP.Net MVC) along with Simple.Data in the data access level.

I'm wrapping my db connection like this:

`AdoAdapter.ConnectionCreated += (o, args) => args.OverrideConnection(new ProfiledDbConnection((DbConnection)args.Connection, MiniProfiler.Current));`

I'm seeing SqlTiming throwing an InvalidOperationException from time to time, especially when the site is under load.

`System.InvalidOperationException: Operation is not valid due to the current state of the object`

Full stacktrace below. Any ideas what might be causing this to happen?

`Exception:'System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at StackExchange.Profiling.SqlTiming..ctor(IDbCommand command, SqlExecuteType type, MiniProfiler profiler) in c:\TeamCity\buildAgent\work\1de24adb938b932d\StackExchange.Profiling\SqlTiming.cs:line 43
   at StackExchange.Profiling.SqlProfiler.ExecuteStartImpl(IDbCommand command, SqlExecuteType type) in c:\TeamCity\buildAgent\work\1de24adb938b932d\StackExchange.Profiling\SqlProfiler.cs:line 40
   at StackExchange.Profiling.SqlProfilerExtensions.ExecuteStart(SqlProfiler sqlProfiler, IDbCommand command, SqlExecuteType type) in c:\TeamCity\buildAgent\work\1de24adb938b932d\StackExchange.Profiling\SqlProfiler.cs:line 97
   at StackExchange.Profiling.MiniProfiler.StackExchange.Profiling.Data.IDbProfiler.ExecuteStart(IDbCommand profiledDbCommand, SqlExecuteType executeType) in c:\TeamCity\buildAgent\work\1de24adb938b932d\StackExchange.Profiling\MiniProfiler.IDbProfiler.cs:line 19
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in c:\TeamCity\buildAgent\work\1de24adb938b932d\StackExchange.Profiling\Data\ProfiledDbCommand.cs:line 237
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
   at Simple.Data.Ado.DbCommandExtensions.TryExecuteReader(IDbCommand command)
   at Simple.Data.Ado.DataReaderEnumerable.DataReaderEnumerator.ExecuteReader()
   at Simple.Data.Ado.DataReaderEnumerable.DataReaderEnumerator.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator2.MoveNext()
   at Simple.Data.CastEnumerable1.CastEnumerator.MoveNext()
   at Simple.Data.CastEnumerable1.CastEnumerator.MoveNext()
   at System.Collections.Generic.List1..ctor(IEnumerable1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable1 source)
   at Simple.Data.SimpleQuery.ToList[T]()
   at DataAccess.SimpleData.xxxxxxxRepository.GetAllxxxxxxIds(Guid xxxx) in xxxx
   at xxxx.Authentication.xxxxUserMapper.GetUserFromIdentifier(Guid identifier, NancyContext context) in xxxx
   at Castle.Proxies.Invocations.IUserMapper_GetUserFromIdentifier.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Infrastructure.Instrumentation.GenericProfilerInteceptor.Intercept(IInvocation invocation) in xxxx
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.IUserMapperProxy.GetUserFromIdentifier(Guid identifier, NancyContext context)
   at Nancy.Authentication.Forms.FormsAuthentication.<>c__DisplayClass7.<GetLoadAuthenticationHook>b__6(NancyContext context)
   at Nancy.BeforePipeline.<>c__DisplayClass4.<Wrap>b__3(NancyContext ctx, CancellationToken ct)`

**Comment by yellis** [comment]
What are you doing when this happens?

This doesnt happen when you aren't using profiler?

Stack Trace has error happening when the `SqlTiming` object is being initialized, before any actual work is being done.

**Comment by kzhen** [comment]
This has only started happening when using MiniProfiler. 

I am running a load test (using VS) locally so the website is running on IIS Express. The load test is basically jsut browsing to different pages of the website and logging in. It happens in a few different places, but all are related to SQL queries.

**Comment by kzhen** [comment]
I can confirm that this also occurs when the web app is running on IIS.

In case it helps, I'm hooking MiniProfiler into my Nancy app like this:

`public class WebPerformanceStartup : IApplicationStartup
    {
        private readonly IRouteResolver routeResolver;
        public DrDrWebPerformanceStartup(IRouteResolver routeResolver)
        {
            this.routeResolver = routeResolver;
        }

        public void Initialize(IPipelines pipelines)
        {
            pipelines.BeforeRequest.AddItemToStartOfPipeline(context =>
            {
                var route = routeResolver.Resolve(context);

                if (route == null || route.Route == null || route.Route.Description == null) // probably not necessary but don't want the chance of losing visibility on anything
                {
                    MiniProfiler.Start(string.Format("{0}{1}", context.Request.Method, context.Request.Url.ToString()));
                }
                else
                {
                    MiniProfiler.Start(string.Format("{0}{1}", route.Route.Description.Method, route.Route.Description.Path));
                }
                return null;
            });
            pipelines.OnError.AddItemToEndOfPipeline(
                (context, ex) =>
                {
                    return null;
                });
            pipelines.AfterRequest.AddItemToEndOfPipeline((ctx) =>
            {
                MiniProfiler.Stop();
                if (MiniProfiler.Settings.Storage != null)
                {
                    MiniProfiler.Settings.Storage.Save(MiniProfiler.Current);
                }
            });
        }
    }`

**Comment by kzhen** [comment]
I can confirm that this also occurs when the web app is running on IIS.

In case it helps, I'm hooking MiniProfiler into my Nancy app like this:

`public class WebPerformanceStartup : IApplicationStartup
    {
        private readonly IRouteResolver routeResolver;
        public DrDrWebPerformanceStartup(IRouteResolver routeResolver)
        {
            this.routeResolver = routeResolver;
        }

        public void Initialize(IPipelines pipelines)
        {
            pipelines.BeforeRequest.AddItemToStartOfPipeline(context =>
            {
                var route = routeResolver.Resolve(context);

                if (route == null || route.Route == null || route.Route.Description == null) // probably not necessary but don't want the chance of losing visibility on anything
                {
                    MiniProfiler.Start(string.Format("{0}{1}", context.Request.Method, context.Request.Url.ToString()));
                }
                else
                {
                    MiniProfiler.Start(string.Format("{0}{1}", route.Route.Description.Method, route.Route.Description.Path));
                }
                return null;
            });
            pipelines.OnError.AddItemToEndOfPipeline(
                (context, ex) =>
                {
                    return null;
                });
            pipelines.AfterRequest.AddItemToEndOfPipeline((ctx) =>
            {
                MiniProfiler.Stop();
                if (MiniProfiler.Settings.Storage != null)
                {
                    MiniProfiler.Settings.Storage.Save(MiniProfiler.Current);
                }
            });
        }
    }`

**Comment by kzhen** [comment]
This was resolved by using the correct ProfilerProvider, WebRequestProfilerProvider rather than the Singleton.
