### ISSUE TITLE
SaveProfiler - Object reference not set to an instance of an object BaseProfilerProvider.cs:line 77

### ISSUE THREAD

**Issue by thnk2wn** [MiniProfiler/dotnet#120]
I'm using MiniProfiler 3.2.0.157 in a Windows app. I have an updated version of MiniProfiler.Windows that I modified the source for to work with the latest MiniProfiler. It's been working fine but suddenly I'm receiving the below and can't tell where things have gone wrong. It looks like maybe MiniProfiler.Current is null and SaveProfiler method isn't expecting that. I suppose a null check could be added there or a better exception but the root problem isn't there I'm sure. Ideas?

System.NullReferenceException was unhandled by user code
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=MiniProfiler
  StackTrace:
       at StackExchange.Profiling.BaseProfilerProvider.SaveProfiler(MiniProfiler current) in c:\TeamCity\buildAgent\work\a743336045964cbc\StackExchange.Profiling\BaseProfilerProvider.cs:line 77
       at MiniProfiler.Windows.ConsoleProfilingProvider.Stop(Boolean discardResults)
       at StackExchange.Profiling.MiniProfiler.Stop(Boolean discardResults) in c:\TeamCity\buildAgent\work\a743336045964cbc\StackExchange.Profiling\MiniProfiler.cs:line 309
       at MiniProfiler.Windows.ConsoleProfiling.StopAndGetProfiler()
       at MiniProfiler.Windows.ConsoleProfiling.StopAndGetFriendlyOutput(String& error)
  InnerException:

**Comment by thnk2wn** [comment]
Changed the ConsoleProfilingProvider Stop method to include a null check and seems to be good. Can't quite trace down yet why and where it's getting null but for now this seems to work.

    public override void Stop(bool discardResults)
    {
        if (_profiler != null)
            SaveProfiler(_profiler);
        else
        {
            LastWarning = "Profiler is null; skipped SaveProfiler()";
            Trace.TraceWarning(LastWarning);
         }
    }

**Comment by thnk2wn** [comment]
Nevermind, the null profiler appeared to be an issue with some bad async/await code.
