### ISSUE TITLE
Object Reference Error: dotnet ef migrations remove

### ISSUE THREAD

**Issue by Wayne-Mather** [MiniProfiler/dotnet#238]
Hi,

I get the following error when trying to undo a migration. Adding migrations works, its only the remove. 

I can validate this by just commenting out the relevant extensions in the DI configuration step.

So to recap when miniprofiler setup and working:

- dotnet ef migrations add XXXX -- works
- dotnet ef migrations remove -- fails

```

info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\wmather\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
info: Microsoft.EntityFrameworkCore.Infrastructure[100403]
      Entity Framework Core 2.0.0-rtm-26452 initialized 'ApplicationDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: SensitiveDataLoggingEnabled MaxPoolSize=128 MigrationsAssembly=PfmsWeb
System.NullReferenceException: Object reference not set to an instance of an object.
   at StackExchange.Profiling.Data.RelationalDiagnosticListener.OnNext(KeyValuePair`2 kv) in C:\projects\dotnet\src\MiniProfiler.EntityFrameworkCore\RelationalDiagnosticListener.cs:line 114
   at System.Diagnostics.DiagnosticListener.Write(String name, Object value)
   at Microsoft.EntityFrameworkCore.Internal.RelationalLoggerExtensions.ConnectionOpened(IDiagnosticsLogger`1 diagnostics, IRelationalConnection connection, DateTimeOffset startTime, TimeSpan duration, Boolean async)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass18_0.<Exists>b__0(DateTime giveUp)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass12_0`2.<Execute>b__0(DbContext c, TState s)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, Func`2 operation, Func`2 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerDatabaseCreator.Exists(Boolean retryOnNotExists)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.GetAppliedMigrations()
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.RemoveMigration(String projectDir, String rootNamespace, Boolean force)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.RemoveMigration(String contextType, Boolean force)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.RemoveMigrationImpl(String contextType, Boolean force)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.RemoveMigration.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Object reference not set to an instance of an object.

```

**Comment by NickCraver** [comment]
Which version of the MiniProfiler packages are you on? A full paste of your package references from your .csproj would be most helpful here :)

**Comment by Wayne-Mather** [comment]
@NickCraver  Sure, included below.

If you cannot replicate the problem let me know and I will see if I can create repo that shows the problem I have. 

This solution has come from the DNX Beta days, so my BLL is still actually an ASP.NET Core MVC DLL as that was the only way to do it back then in-case that too matters :) 

My context is located in the BLL and not the main asp.net site. And incase it matters here is an excerpt of that context main functions

        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)  : base(options)
        {
            this.TransactionsSupported = true;
            this.AlreadyInTransaction = false;
            Database.SetCommandTimeout(9000);
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);
        }
       

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
            new PfmsContextBuilder().CreatedPfmsModelBindings(builder);
        }

**Main Project**

&lt;Project Sdk="Microsoft.NET.Sdk.Web"&gt;

  &lt;PropertyGroup&gt;
    &lt;VersionPrefix&gt;1.3.0.0&lt;/VersionPrefix&gt;
    &lt;Version&gt;1.3.0.0&lt;/Version&gt;
    &lt;TargetFramework&gt;netcoreapp2.0&lt;/TargetFramework&gt;
  &lt;/PropertyGroup&gt;

  &lt;ItemGroup&gt;
    &lt;None Remove="Properties\PublishProfiles\Default.pubxml" /&gt;
  &lt;/ItemGroup&gt;

  &lt;ItemGroup&gt;
    &lt;ProjectReference Include="..\Pfms.BLL\Pfms.BLL.csproj" /&gt;
  &lt;/ItemGroup&gt;

  &lt;ItemGroup&gt;
    &lt;PackageReference Include="MediatR" Version="3.0.1" /&gt;
    &lt;PackageReference Include="MiniProfiler.AspNetCore.Mvc" Version="4.0.0-alpha8-165" /&gt;
    &lt;PackageReference Include="MiniProfiler.EntityFrameworkCore" Version="4.0.0-alpha8-165" /&gt;
    &lt;PackageReference Include="NuGet.CommandLine" Version="4.1.0" /&gt;
    &lt;PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" /&gt;
    &lt;PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.0" PrivateAssets="All" /&gt;
    &lt;PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.0" PrivateAssets="All" /&gt;
  &lt;/ItemGroup&gt;

  &lt;ItemGroup&gt;
    &lt;DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0" /&gt;
    &lt;DotNetCliToolReference Include="Microsoft.Extensions.SecretManager.Tools" Version="2.0.0" /&gt;
    &lt;DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0" /&gt;
    &lt;DotNetCliToolReference Include="Microsoft.DotNet.Watcher.Tools" Version="2.0.0" /&gt;
  &lt;/ItemGroup&gt;

&lt;/Project&gt;

**BLL Project**

&lt;Project Sdk="Microsoft.NET.Sdk.Web"&gt;

  &lt;PropertyGroup&gt;
    &lt;VersionPrefix&gt;1.3.0.0&lt;/VersionPrefix&gt;
    &lt;Version&gt;1.3.0.0&lt;/Version&gt;
    &lt;TargetFramework&gt;netcoreapp2.0&lt;/TargetFramework&gt;
    &lt;ApplicationIcon /&gt;
    &lt;OutputType&gt;Library&lt;/OutputType&gt;
    &lt;StartupObject /&gt;
    &lt;RootNamespace&gt;Pfms.Bll&lt;/RootNamespace&gt;
  &lt;/PropertyGroup&gt;

  &lt;ItemGroup&gt;
    &lt;PackageReference Include="MediatR" Version="3.0.1" /&gt;
    &lt;PackageReference Include="StructureMap" Version="4.5.2" /&gt;
    &lt;PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" /&gt;
    &lt;PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.0" PrivateAssets="All" /&gt;
    &lt;PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.0" PrivateAssets="All" /&gt;
  &lt;/ItemGroup&gt;


&lt;/Project&gt;

**Comment by NickCraver** [comment]
Can you please try bumping to current (4.0.0-alpha9-00206) and see if the issue continues? At the least, it'll give me a better idea of what's happening :) I *think* this is the same issue fixed for another a while ago that latest code resolves...let's find out :)

**Comment by Wayne-Mather** [comment]
Will do that am located gmt +930 so you will the results tomorrow.
Hopefully solves the issue so easier for you :)

**Comment by Wayne-Mather** [comment]
@NickCraver  - I Can confirm updating to the latest alpha9 does look like it solve the problem. I will mark this as closed and keep you informed if there are any further issues noted.

What is the best way to monitor for new releases and the changes in them?
