### ISSUE TITLE
MiniProfiler shouldn't break application under any circumstances

### ISSUE THREAD

**Issue by MartinDemberger** [MiniProfiler/dotnet#358]
I just added MiniProfiler to my business application. Now I have the second case where a error on my using of MiniProfiler breaks the hole application. In my opinion profiling like logging shouldn't break the application even if it's misconfigured or misused.

I suggest for MiniProfiler to handle all Exceptions inside itself to a default method which can be logged, ignored or rethrown dependent of the application.

**Comment by NickCraver** [comment]
What error are you actually getting? Let's start there.

**Comment by MartinDemberger** [comment]
I had a not null constraint on my db column. This was no problem to fix but as I already wrote this shouldn't break my business logic.

**Comment by NickCraver** [comment]
Do you have a stack trace showing how MiniProfiler broke anything here? We're talking about abstracts but the concrete case here isn't something that makes sense...a stack trace would. Or even a concrete error. Did this problem happen because you added MiniProfiler? Did it work fine without it, but not with it? Or did it arise while you were already using MiniProfiler and made changes elsewhere?

MiniProfiler works by acting as a layer in the database area, so while it's in the stack trace, it's almost never the actual cause (we see this reported all the time). The actual problem is usually in the ADO.NET layer, and would happen with or without MiniProfiler there.

So...an example really helps. Do you have one?

**Comment by MartinDemberger** [comment]
I reactivated the NOT NULL-Constraint on the column MiniProfilerTimings.CustomTimingsJson. Now I get the following Exception

```
System.Data.SqlClient.SqlException
  HResult=0x80131904
  Message=Cannot insert the value NULL into column 'CustomTimingsJson', table 'EPlatoDiagnostics.dbo.MiniProfilerTimings'; column does not allow nulls. INSERT fails.
The statement has been terminated.
  Source=.Net SqlClient Data Provider
  StackTrace:
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader(Boolean isInternal, Boolean forDescribeParameterEncryption)
   at System.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, String endMethod, Boolean isInternal)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapper.SqlMapper.<ExecuteMultiImplAsync>d__38.MoveNext() in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 654
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at StackExchange.Profiling.Storage.SqlServerStorage.<SaveAsync>d__12.MoveNext() in D:\ePlato\RootNine.Diagnostics.Persistence\SqlServerStorage.cs:line 612
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at StackExchange.Profiling.DefaultProfilerProvider.<SaveAsync>d__8.MoveNext() in C:\projects\dotnet\src\MiniProfiler.Shared\ProfileProviders\DefaultProfilerProvider.cs:line 112
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at StackExchange.Profiling.DefaultProfilerProvider.<StoppedAsync>d__6.MoveNext() in C:\projects\dotnet\src\MiniProfiler.Shared\ProfileProviders\DefaultProfilerProvider.cs:line 78
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at StackExchange.Profiling.MiniProfiler.<StopAsync>d__79.MoveNext() in C:\projects\dotnet\src\MiniProfiler.Shared\MiniProfiler.cs:line 243
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at RootNine.ServiceInitializer.<InitService>d__5.MoveNext() in D:\ePlato\RootNine.ToolBox\Services\ServiceInitializer.cs:line 62
```
The Exception isn't catched anywhere so my ServiceInitializer get an Exception and the hole application is stopping. Don't wonder about the path of SqlServerStorage. I copied the complete file because of #186 .

**Comment by NickCraver** [comment]
I'm not understanding how you're getting the first error - the definition of the table is: https://github.com/MiniProfiler/dotnet/blob/master/src/MiniProfiler.Providers.SqlServer/SqlServerStorage.cs#L414-L426

```sql
CREATE TABLE {MiniProfilerTimingsTable}
(
    RowId                               integer not null identity constraint PK_{MiniProfilerTimingsTable} primary key clustered,
    Id                                  uniqueidentifier not null,
    MiniProfilerId                      uniqueidentifier not null,
    ParentTimingId                      uniqueidentifier null,
    Name                                nvarchar(200) not null,
    DurationMilliseconds                decimal(15,3) not null,
    StartMilliseconds                   decimal(15,3) not null,
    IsRoot                              bit not null,
    Depth                               smallint not null,
    CustomTimingsJson                   nvarchar(max) null
);
```
...so `CustomTimingsJson` allows `null`. Did you change the definition of the SQL table?

**Comment by NickCraver** [comment]
@MartinDemberger if you have more information here, I'm happy to re-open. From the given info, it looks like the definition of the tables was changed which...yep, that's going to break things. Changing the schema underneath any application that depends on it will have such issues.
