### ISSUE TITLE
MiniProfiler JS/Middleware Error: The JSON value could not be converted to System.Nullable

### ISSUE THREAD

**Issue by ckarcz** [MiniProfiler/dotnet#449]
Hi,

I am using MiniProfiler v4.1.0 on ASP.NET Core 3.1.

I am using the web ui script (in swashbuckle custom index.html):

```
<script async="async" id="mini-profiler" src="/profiler/includes.min.js?v=4.0.138+gcc91adf599" data-version="4.0.138+gcc91adf599" data-path="/profiler/" data-current-id="4ec7c742-49d4-4eaf-8281-3c1e0efa748a" data-ids="" data-position="Left" data-authorized="true" data-max-traces="15" data-toggle-shortcut="Alt+P" data-trivial-milliseconds="2.0" data-ignored-duplicate-execute-types="Open,OpenAsync,Close,CloseAsync"></script>
```
I get the following error thrown that seems to come from MiniProfiler. It seems to only happens when the swagger UI first loads.

```
The JSON value could not be converted to System.Nullable`1[System.Guid]. Path: $.Id | LineNumber: 0 | BytePositionInLine: 8.
```

Exception:

```
System.Text.Json.JsonException: The JSON value could not be converted to System.Nullable`1[System.Guid]. Path: $.Id | LineNumber: 0 | BytePositionInLine: 8.
 ---> System.FormatException: The JSON value is not in a supported Guid format.
   at System.Text.Json.Utf8JsonReader.GetGuid()
   at System.Text.Json.Serialization.Converters.JsonConverterGuid.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.JsonPropertyInfoNullable`2.OnRead(ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonPropertyInfo.Read(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& readStack, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadCore(JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at StackExchange.Profiling.MiniProfilerMiddleware.GetSingleProfilerResultAsync(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 323
   at StackExchange.Profiling.MiniProfilerMiddleware.HandleRequest(HttpContext context, PathString subPath) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 217
   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 125
   at Elastic.Apm.AspNetCore.ApmMiddleware.InvokeAsync(HttpContext context)
   at Elastic.Apm.AspNetCore.ApmMiddleware.InvokeAsync(HttpContext context)
   at Elastic.Apm.AspNetCore.ApmMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by NickCraver** [comment]
What storage are you using to back MiniProfiler? I'm not sure what's going on here - if it's a null Id or...something else. Any chance you see what ID it's trying to fetch?

**Comment by ckarcz** [comment]
Hi @NickCraver . Thanks for replying.

I have not configured any of the options, leaving them to defaults:

```
if (Configuration.GetValue<bool>("MiniProfiler:Enabled"))
{
    services.AddMiniProfiler(options => options.RouteBasePath = "/profiler")
            .AddEntityFramework();
}
```

To clarify, this is occurring when using the HTML js script markup (I shared in the original post) in a custom Swagger html document (for Swashbuckle). The script tag I based on [this](https://github.com/AnthonyGiretti/commonfeatures-webapi-aspnetcore/tree/master/WebApiDemo).

The error does **only occur at the initial Swagger UI rendering**. After this there are no more errors. Though fixing this would be nice to prevent Errors logged/raised.

Also you can see that the top non MS/framework stack step is: 
```StackExchange.Profiling.MiniProfilerMiddleware.GetSingleProfilerResultAsync```

**Here is the request as sniffed in Fiddler:**

```
POST http://localhost:4201/profiler/results HTTP/1.1
Host: localhost:4201
Connection: keep-alive
Content-Length: 9
Accept: application/json, text/javascript, */*; q=0.01
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
Content-Type: application/json
Origin: http://localhost:4201
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Referer: http://localhost:4201/docs/index.html
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9

{"Id":""}
```

**Note the empty string Id field in the body json object**. 

I assume the middleware just needs to be updated to handle (ignore) empty string values. Or the script not send an empty string Id.

Cheers,
Chris

**Comment by NickCraver** [comment]
Alrighty, this is fixed for the next release (it won't even make the request) - thanks for the report!
