### ISSUE TITLE
Collection was modified when running in integration tests

### ISSUE THREAD

**Issue by ChristopherHaws** [MiniProfiler/dotnet#522]
I have MiniProfiler in my ASP.NET Core app and I have an integration test suit that uses ASP.NET Core's WebApplicationFactory to create and destroy a new "web server" per test fixture. In a lot of my test runs, I keep running into an issue where MiniProfiler is disposing the `DiagnosticInitializer` which is iterating on a n enumerable that gets modified.

```
[Test Class Cleanup Failure]: System.InvalidOperationException : Collection was modified; enumeration operation may not execute.


Stack trace
at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
at StackExchange.Profiling.Internal.DiagnosticInitializer.Dispose(Boolean disposing) in C:\projects\dotnet\src\MiniProfiler.Shared\DiagnosticInitializer.cs:line 64
at StackExchange.Profiling.Internal.DiagnosticInitializer.Dispose() in C:\projects\dotnet\src\MiniProfiler.Shared\DiagnosticInitializer.cs:line 54
at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.DisposeAsync()
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.Extensions.Hosting.Internal.Host.DisposeAsync()
at Microsoft.Extensions.Hosting.Internal.Host.Dispose()
at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.Dispose(Boolean disposing)
at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.Dispose()
```

**Comment by NickCraver** [comment]
Thanks for the report and the stack! I'm not exactly sure what race happens here overall but no matter: the area touched should be touched rarely for most apps and adding a touch of locking is not an issue. The next CI build will have this resolved in a moment :)
