### ISSUE TITLE
Cannot apply changes to property StackExchange.Profiling.TimingDebugInfo.RichHtmlStack

### ISSUE THREAD

**Issue by jerviscui** [MiniProfiler/dotnet#588]
I want test MiniProfiler in .Net 6.
When I used the RedisStorage, I get a Exception.

```csharp
services.AddMiniProfiler(options =>
{
    options.Storage =
        new RedisStorage("...") { CacheDuration = TimeSpan.FromMinutes(30) };
}).AddEntityFramework();
```

Will throw a Exception when the storage save:

> Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: Cannot apply changes to property StackExchange.Profiling.TimingDebugInfo.RichHtmlStack
         at ProtoBuf.Serializers.PropertyDecorator.SanityCheck(TypeModel model, PropertyInfo property, IProtoSerializer tail, Boolean& writeValue, Boolean nonPublic, Boolean allowInternal) in C:\Code\protobuf-net\src\protobuf-net\Serializers\PropertyDecorator.cs:line 41
         at ProtoBuf.Serializers.PropertyDecorator..ctor(TypeModel model, Type forType, PropertyInfo property, IProtoSerializer tail) in C:\Code\protobuf-net\src\protobuf-net\Serializers\PropertyDecorator.cs:line 25
         at ProtoBuf.Meta.ValueMember.BuildSerializer() in C:\Code\protobuf-net\src\protobuf-net\Meta\ValueMember.cs:line 579
         at ProtoBuf.Meta.MetaType.BuildSerializer() in C:\Code\protobuf-net\src\protobuf-net\Meta\MetaType.cs:line 396
         at ProtoBuf.Meta.MetaType.get_Serializer() in C:\Code\protobuf-net\src\protobuf-net\Meta\MetaType.cs:line 372
         at ProtoBuf.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest) in C:\Code\protobuf-net\src\protobuf-net\Meta\RuntimeTypeModel.cs:line 803
         at ProtoBuf.ProtoWriter.WriteObject(Object value, Int32 key, ProtoWriter writer) in C:\Code\protobuf-net\src\protobuf-net\ProtoWriter.cs:line 35
         at proto_3(Object , ProtoWriter )
         at ProtoBuf.Serializers.CompiledSerializer.ProtoBuf.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest)
         at ProtoBuf.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest)
         at ProtoBuf.ProtoWriter.WriteObject(Object value, Int32 key, ProtoWriter writer)
         at proto_3(Object , ProtoWriter )
         at ProtoBuf.Serializers.CompiledSerializer.ProtoBuf.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest)
         at ProtoBuf.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest)
         at ProtoBuf.ProtoWriter.WriteObject(Object value, Int32 key, ProtoWriter writer)
         at proto_3(Object , ProtoWriter )
         at ProtoBuf.Serializers.CompiledSerializer.ProtoBuf.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest)
         at ProtoBuf.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest)
         at ProtoBuf.ProtoWriter.WriteObject(Object value, Int32 key, ProtoWriter writer)
         at proto_1(Object , ProtoWriter )
         at ProtoBuf.Serializers.CompiledSerializer.ProtoBuf.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest)
         at ProtoBuf.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest)
         at ProtoBuf.Meta.TypeModel.SerializeCore(ProtoWriter writer, Object value)
         at ProtoBuf.Meta.TypeModel.Serialize(Stream dest, Object value, SerializationContext context)
         at ProtoBuf.Meta.TypeModel.Serialize(Stream dest, Object value)
         at ProtoBuf.Serializer.Serialize[T](Stream destination, T instance)
         at StackExchange.Profiling.Storage.Internal.RedisStorageHelpers.ToRedisValue(MiniProfiler profiler)
         at StackExchange.Profiling.Storage.RedisStorage.Save(MiniProfiler profiler)
         at MiniprofilerTest.MVC.Pages.IndexModel.OnGet()
         at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.NonGenericTaskHandlerMethod.Execute(Object receiver, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeHandlerMethodAsync()
         at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeNextPageFilterAsync()
         at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Rethrow(PageHandlerExecutedContext context)
         at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeInnerFilterAsync()
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by NickCraver** [comment]
@mgravell does this ring a bell at all? I'm not sure why Protobuf would try to be setting this, declaration is:

```cs
    [DataContract]
    public class TimingDebugInfo
    {
        [DataMember(Order = 1)]
        public string RichHtmlStack => StackTraceUtils.HtmlPrettify(RawStack.ToString(), CommonStackStart);
```

Am I missing the obvious on the definition side or does this raise any memories of a previous protobuf-net issue where I should bump the dependency? It's currently at `2.4.6`.

**Comment by mgravell** [comment]
protobuf-net won't like that - it wants to be able to round-trip things, and it clearly can't here. It is possible to configure protobuf-net to ignore the property, though - including at runtime, if we don't have a ref directly (for protobuf-net attributes).
